language: java
  - oraclejdk8
language: node_js
script:
- curl -s get.sdkman.io | bash
- source "$HOME/.sdkman/bin/sdkman-init.sh"
- echo sdkman_auto_answer=true > ~/.sdkman/etc/config
- source "/home/travis/.sdkman/bin/sdkman-init.sh"
- sdk install grails
- cd "server"
- grails test-app
- cd "../client"
- ng test
- cd "../"
- ./gradlew build